### ISSUE TITLE
Suggestion: Use `std::unique_ptr` to manage memory resource may be better?

### ISSUE THREAD

**Issue by Yxa2111** [chardon55/libpgfe#1]
I found there are many of `new` and `delete` in source code, using `std::unique_ptr` to control them may be better? It can release memory automatically by `RAII` to avoid memory leak when forgot `delete ptr;`.

More about `std::unique_ptr`: https://en.cppreference.com/w/cpp/memory/unique_ptr

**Comment by chardon55** [comment]
I'll think about it.

**Comment by chardon55** [comment]
The updates has been completed and merged into 'dev' branch, which will appear in v0.6.0.
